<a href="https://colab.research.google.com/github/ZuzaSzara/machine_learning_bootcamp_I/blob/main/supervised/01_basics/02_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Utworzenie kopii danych](#2)
4. [Sprawdzenie braków](#3)
5. [Uzupełnienie braków - SimpleImputer](#4)
6. [Braki danych w szeregach czasowych](#5)

### <a name='0'></a> Import bibliotek

In [3]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

### <a name='1'></a> Wygenerowanie danych

In [4]:
data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

### <a name='2'></a> Utworzenie kopii danych

In [5]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   6 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes

### <a name='3'></a> Sprawdzenie braków

In [6]:
df.isnull()

    size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [7]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(5)

### <a name='4'></a> Uzupełnienie braków - SimpleImputer

### <a name='5'></a> Braki danych w szeregach czasowych

Usunięcie braków

Wypełnienie braków stałą wartością 0

Wypełnienie braków średnią

Zastosowanie interpolacji

Wypełnienie braków metodą forward fill

Wypełnienie braków metodą backward fill